//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreundeVerwaltung.DatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int PersonID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }

        public People(int PersonID, int CustomerID, string FirstName, string LastName)
        {
            this.PersonID = PersonID;
            this.CustomerID = CustomerID;
            this.FirstName = FirstName;
            this.LastName = LastName;
        }

        public People() { }
    }
}
